### PR TITLE
add missing test on toastActions in SW

### PR DESCRIPTION
**Pull request by shprink**
in the same file we test if `toastActions` is defined:

```
if (toastActions) {
          toastActions.showToast({
            message: '{$ newVersionAvailable $}',
            action: {
              title: '{$ refresh $}',
              callback: tapHandler,
            },
            duration: 0,
          });
        }
```

but here no 🤔 Adding the test to fix a FF issue

### CODE REVIEW

**Comment by davinkevin** [comment]
This should a pr in the hoverboard project ?

**Review by davinkevin — COMMENTED** [review]
This should be on a PR for the hoverboard project? That would be simple to maintain if it is on their side...

**Comment by shprink** [comment]
Fixed upstream: https://github.com/gdg-x/hoverboard/pull/420

**Comment by shprink** [comment]
@davinkevin c'est merged upstream, je te laisse recup le commit ;)

**Comment by davinkevin** [comment]
Done with rewind of master to be sync with hoverboard-v2.

**Pull request closed without merging**
